stages:
- name: build
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: go build
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: golangsun
      pushRemote: true
      registry: index.docker.io
timeout: 60
