apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # adjust name for your deployment
  namespace: default # specify your namespace to apply deployment
spec:
  replicas: 1 # adjust number of replicas for your deployment
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx # adjust name of container
        image: nginx:1.14.2 # adjust image_name and tag for your container
        ports:
        - containerPort: 80 # adjust port for your container
---
apiVersion: v1
kind: Service
metadata:
  name: my-svc # adjust name for your service
  namespace: default # specify your namespace to apply service
spec:
  selector:
    app: nginx # change label selector to match your backend pod
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 644
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ceshi
  namespace: default
spec:
  rules:
    - host: ww.ww.ww
      http:
        paths:
          - backend:
              service:
                name: my-svc
                port:
                  number: 443
            path: /
            pathType: ImplementationSpecific