apiVersion: core.kubeadmiral.io/v1alpha1
kind: OverridePolicy
metadata:
  name: op-policay
spec:
  overrideRules:
  - overriders:
      jsonpatch:
      - operator: replace
        path: /spec/template/spec/containers/0/image
        value: nginx:alpine
    targetClusters:
      clusters:
      - cco9roj0pus0qsciikafg  # 替换为您的成员集群
